version: '3.1'
#Docker compose file for integration testing
services:
#  mysql:
#    image: mysql:latest
#    container_name: mysql
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASS}
#      MYSQL_ROOT_HOST: ${MYSQL_ROOT_USER}
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_USER}
#    networks:
#      - integration

  spark:
    image: bitnami/spark:latest
    container_name: spark
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - integration
  python:
    image: python:latest
    container_name: python
    command: bash -c "pip install --upgrade pip && pip install -r ./app/requirements.txt && python main_spark_extraction.py"
    depends_on:
      - spark
    volumes:
      - ../requirements.txt:/app/requirements.txt
      - ../dbt/fballproject/seeds:/app/dbt/seeds
    networks:
      - integration
networks:
  integration:
    driver: bridge